/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lightsoff;

/**
 *
 * @author 33781
 */
public class fenetreDeJeu extends javax.swing.JFrame {

    Grille GrilleJeu = new Grille();
    /**
     * Creates new form fenetreDeJeu
     */
    public fenetreDeJeu() {
        initComponents();
        
        for (int i = 4; i >= 0; i--){
            for ( int j = 0; j < 5; j++){
                CelluleGraphique cellGraph = new CelluleGraphique(GrilleJeu.cellules[i][j]);
                cellGraph.addActionListener((java.awt.event.ActionEvent evt) -> {
                   CelluleLumineuse c = cellGraph.celluleAssociee;
                   cellGraph.celluleAssociee.setCelluleJouee();
                   cellGraph.celluleAssociee.changerEtat();
                   GrilleJeu.changerVoisin();
                   panneau_grille.repaint();
                });

                panneau_grille.add(cellGraph);
            }
        }
    }
    
    public void initialiserpartie() {
        GrilleJeu.DebutPartie();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panneau_grille = new javax.swing.JPanel();
        panneau_info = new javax.swing.JPanel();
        nombre_essais = new javax.swing.JLabel();
        partie = new javax.swing.JButton();
        essais = new javax.swing.JLabel();
        lbl_essais = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panneau_grille.setBackground(new java.awt.Color(0, 0, 204));
        panneau_grille.setLayout(new java.awt.GridLayout(5, 5));

        panneau_info.setBackground(new java.awt.Color(204, 255, 204));

        nombre_essais.setText("Nombre d'essais :");

        partie.setText("Démarrer une partie");
        partie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partieActionPerformed(evt);
            }
        });

        lbl_essais.setText("0");

        javax.swing.GroupLayout panneau_infoLayout = new javax.swing.GroupLayout(panneau_info);
        panneau_info.setLayout(panneau_infoLayout);
        panneau_infoLayout.setHorizontalGroup(
            panneau_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panneau_infoLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(partie)
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(panneau_infoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(nombre_essais)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_essais)
                .addGap(54, 54, 54)
                .addComponent(essais, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panneau_infoLayout.setVerticalGroup(
            panneau_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneau_infoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panneau_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre_essais)
                    .addComponent(essais)
                    .addComponent(lbl_essais))
                .addGap(18, 18, 18)
                .addComponent(partie)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panneau_grille, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panneau_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panneau_grille, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(panneau_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        setBounds(0, 0, 839, 530);
    }// </editor-fold>//GEN-END:initComponents

    private void partieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partieActionPerformed
        // TODO add your handling code here:
        panneau_grille.repaint();
        partie.setEnabled(false);
    }//GEN-LAST:event_partieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fenetreDeJeu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel essais;
    private javax.swing.JLabel lbl_essais;
    private javax.swing.JLabel nombre_essais;
    private javax.swing.JPanel panneau_grille;
    private javax.swing.JPanel panneau_info;
    private javax.swing.JButton partie;
    // End of variables declaration//GEN-END:variables

}
