/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package premièreinterfacegraphique_colas.demangeot;

/**
 *
 * @author 33781
 */
public class FenêtrePrincipale extends javax.swing.JFrame {

    /**
     * Creates new form FenêtrePrincipale
     */
    public FenêtrePrincipale() {
        initComponents();
        System.out.println("Fenetre crée");
        msg_bienvenue.setText("Bonjour le Monde !!!");
        msg_résultat.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msg_bienvenue = new javax.swing.JLabel();
        msg_fin = new javax.swing.JLabel();
        BoutonValidé = new javax.swing.JButton();
        ZonePrénom = new javax.swing.JTextField();
        msg_prénom = new javax.swing.JLabel();
        msg_résultat = new javax.swing.JLabel();
        msg_salaire = new javax.swing.JLabel();
        ZoneSalaire = new javax.swing.JTextField();
        Augmenter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        msg_bienvenue.setText("Hello World !!!");

        msg_fin.setText("Good Bye !");

        BoutonValidé.setText("Cliquez ici ");
        BoutonValidé.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonValidéActionPerformed(evt);
            }
        });

        ZonePrénom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZonePrénomActionPerformed(evt);
            }
        });

        msg_prénom.setText("Entrez votre prénom");

        msg_résultat.setText("Résultat :");

        msg_salaire.setText("Entrez votre salaire :");

        ZoneSalaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZoneSalaireActionPerformed(evt);
            }
        });

        Augmenter.setText("Augmenter le salaire");
        Augmenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AugmenterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(msg_prénom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ZonePrénom, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(msg_bienvenue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BoutonValidé))
                    .addComponent(msg_fin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(msg_résultat)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(msg_salaire)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ZoneSalaire, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(Augmenter)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(msg_bienvenue)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ZonePrénom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(msg_prénom))
                .addGap(31, 31, 31)
                .addComponent(BoutonValidé)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(msg_résultat)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(msg_salaire)
                    .addComponent(ZoneSalaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Augmenter))
                .addGap(16, 16, 16)
                .addComponent(msg_fin)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoutonValidéActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonValidéActionPerformed
        // TODO add your handling code here:
        msg_fin.setText("Au revoir en français");
        String a = ZonePrénom.getText();
        msg_résultat.setText("Bonjour "+a);
        msg_résultat.setVisible(true);
    }//GEN-LAST:event_BoutonValidéActionPerformed

    private void ZonePrénomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZonePrénomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ZonePrénomActionPerformed

    private void ZoneSalaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZoneSalaireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ZoneSalaireActionPerformed

    private void AugmenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AugmenterActionPerformed
        // TODO add your handling code here:
        String salaire = ZoneSalaire.getText();
        int salaire_entier = Integer.parseInt(salaire);
        salaire_entier++;
        ZoneSalaire.setText(salaire_entier+"");
    }//GEN-LAST:event_AugmenterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenêtrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenêtrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenêtrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenêtrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenêtrePrincipale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Augmenter;
    private javax.swing.JButton BoutonValidé;
    private javax.swing.JTextField ZonePrénom;
    private javax.swing.JTextField ZoneSalaire;
    private javax.swing.JLabel msg_bienvenue;
    private javax.swing.JLabel msg_fin;
    private javax.swing.JLabel msg_prénom;
    private javax.swing.JLabel msg_résultat;
    private javax.swing.JLabel msg_salaire;
    // End of variables declaration//GEN-END:variables
}
